
project_id = "nhmhqhhxlcmhufxxifbn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[realtime]
enabled = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions."send-team-invitation"]
verify_jwt = false

[functions."analyze-document"]
verify_jwt = true

[functions."api-analyze-document"]
verify_jwt = false

[functions."send-email"]
verify_jwt = false

[functions."subscribe-email"]
verify_jwt = false

[functions."check-expiring-trials"]
verify_jwt = true

[functions."whop-webhooks"]
verify_jwt = false

[functions."whop-auth"]
verify_jwt = false

[functions."google-config"]
verify_jwt = false

[functions."process-paypal-payment"]
verify_jwt = false

[functions."process-dodo-payment"]
verify_jwt = false

[functions."ai-chat"]
verify_jwt = false

[functions."create-signing-session"]
verify_jwt = true

[functions."get-signing-session"]
verify_jwt = false

[functions."verify-signing-otp"]
verify_jwt = false

[functions."complete-signature"]
verify_jwt = false
