
project_id = "nhmhqhhxlcmhufxxifbn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[realtime]
enabled = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions."send-team-invitation"]
verify_jwt = false
system_import = true

[functions."analyze-document"]
verify_jwt = true
system_import = true

[functions."api-analyze-document"]
verify_jwt = false
system_import = true

[functions."send-email"]
verify_jwt = false
system_import = true

[functions."subscribe-email"]
verify_jwt = false
system_import = true

[functions."check-expiring-trials"]
verify_jwt = true
system_import = true

[functions."whop-webhooks"]
verify_jwt = false
system_import = true

[functions."whop-auth"]
verify_jwt = false
system_import = true

[functions."google-config"]
verify_jwt = false
system_import = true
